language: python

python:
  - "2.7"
  - "3.5"

sudo: true
env: DISPLAY=':99.0'
dist: trusty
addons: # get google-chrome-stable
  chrome: stable

before_script:
  - wget -N http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - export CHROME_BIN=chromium-browser
  - sudo mv -f ~/chromedriver /usr/local/bin/
  - sudo chmod a+x /usr/local/bin/chromedriver
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install: "pip install ."

script:
  - image_search google cats --limit 100
  - image_search bing cats --limit 100
  - image_search google dogs --limit 10 --json
  - image_search bing cats --limit 10 --json
  - rm -rf dataset/

notifications:
  email: false
